remote_theme: vaibhavvikas/jekyll-theme-minimalistic
title: Rhiannon's Homepage
description: It's a website - very much under construction!
color-scheme: dark

navigation:
  - name: My Code Projects
    link: ./MyCodeProjects/about.html
    sub-list:
      - name: CBCFlow
        link: ./MyCodeProjects/cbcflow.html
  - name: Explainers for my Papers
    link: ./ExplainersForMyPapers/about.html
    sub-list:
      - name: Udall & Davis 2023
        link: ./ExplainersForMyPapers/Udall&Davis2023.html