remote_theme: BDHU/minimalist
title: Rhiannon's Homepage
description: It's a website - very much under construction!
color-scheme: dark

navigation:
  - name: SidebarTesting
    link: ./SidebarTesting.html